title: "Atharv Kharbanda"
description: "My personal website"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
author:
  name: "Atharv Kharbanda"
  bio: "Welcome to my personal website."

